all:
  children:
    servers:
      children:
        group1:
          hosts:
            host1:
              ansible_host: 18.185.44.97
              ansible_ssh_private_key_file: /home/micha/.ssh/Key2024.pem
              ansible_user: ubuntu
        group2:
          hosts:
            host2:
              ansible_host: 3.70.248.121
              ansible_ssh_private_key_file: /home/micha/.ssh/Key2024.pem
              ansible_user: ubuntu
        group3:
          hosts:
            host3:
              ansible_host: 3.76.8.154
              ansible_ssh_private_key_file: /home/micha/.ssh/Key2024.pem
              ansible_user: ubuntu
