---
- name: Apply to all servers
  hosts: servers
  become: yes
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
    - name: Ensure Git is installed
      apt:
        name: git
        state: present
    - name: Check Git version
      shell: git -v
      register: git_version_output
    - name: Display Git Version
      debug:
        var: git_version_output.stdout

- name: Apply to group1
  hosts: group1
  become: yes
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
    - name: Ensure Git is installed
      apt:
        name: git
        state: present
    - name: Check Git version
      shell: git -v
      register: git_version_output
    - name: Display Git Version
      debug:
        var: git_version_output.stdout

- name: Apply to group2
  hosts: group2
  become: yes
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
    - name: Ensure Git is installed
      apt:
        name: git
        state: present
    - name: Check Git version
      shell: git -v
      register: git_version_output
    - name: Display Git Version
      debug:
        var: git_version_output.stdout
